### ISSUE TITLE
Az.Storage 1.11.1-preview not catalog signed

### ISSUE THREAD

**Issue by bergmeister** [Azure/azure-powershell#11261]
## Steps to reproduce

```powershell
Install-Module Az # This will install Az 3.5, which will also install Az.Storage 1.12.0. Not required when using the Azure PowerShell task in Az-DevOps
Install-Module -Name Az.Storage -RequiredVersion 1.11.1-preview -AllowPrerelease # because there are cmdlets in the preview that are not yet in 1.12.0
```

```
PackageManagement\Install-Package : The version '1.11.1' of the module 'Az.Storage' being installed is not catalog signed. Ensure that the version '1.11.1' of the module 'Az.Storage' has the catalog file 'Az.Storage.cat' and signed with the same publisher 'CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US' as the previously-installed module 'Az.Storage' with version '1.12.0' under the directory 'C:\Modules\az_3.5.0\Az.Storage\1.12.0'. If you still want to install or update, use -SkipPublisherCheck parameter.
At C:\program files\powershell\6\Modules\PowerShellGet\PSModule.psm1:9508 char:21
```

## Environment data

Azure DevOps hosted image (windows-2019)
Using the Azure PowerShell task with the latest version of Az (3.5)
PowerShell Core 6.2.4

**Comment by dingmeng-xue** [comment]
Storage team, please look into it.

**Comment by blueww** [comment]
@isra-fel 

As I remember, you helped to build Az.Storage 1.11.1-preview, and publish it.
Would you please help to check why the module not catalog signed?

And How to check it in the testing? Gerenally we (feature team) only check the functionality of the module release candidate. If you can share how to check it, we can also test it in the future.

We might need to release a new module to fix this ASAP, as 1.11.1-preview is the latest storage preview module.

**Comment by isra-fel** [comment]
Me and @blueww we can install the preview module locally without any error, so it might be related to the devops env.
- PowerShellGet is out-of-date ?
I'm investigating the issue

**Comment by bergmeister** [comment]
@isra-fel 
A simple repro in Azure DevOps is:
```yaml
pool:
  vmImage: 'windows-2019'
steps:
- task: AzurePowerShell@4
  inputs:
    azureSubscription: REPLACE_WITH_YOUR_SERVICEENDPOINT_NAME
    ScriptType: InlineScript
    Inline: |
     Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
     Install-Module -Name Az.Storage -RequiredVersion 1.11.1-preview -AllowPrerelease
    azurePowerShellVersion: LatestVersion
    pwsh: true
```

Also note that this only started to happen because the Az module in the task got updated from 3.1 to 3.5 recently, which meant that the out of the box version of Az.Storage got increased to 1.12.0. Somehow PowerShellGet did not complain about this before (which it should have). The reason why we have to install `1.11.1-preview`, is because they contain the new Azure Data Lake cmdlets that are not available in the release version of 1.12 yet
