### ISSUE TITLE
az datafactory linked-service create ignores MSI property

### ISSUE THREAD

**Issue by sgutwein** [Azure/azure-powershell#15337]
## Description

Hi,

I have found the issue that the `az datafactory linked-service create` command ignores the `authentication` property. I not sure if I'm using the command correctly as the [documentation](https://docs.microsoft.com/de-de/cli/azure/datafactory/linked-service?view=azure-cli-latest#az_datafactory_linked_service_create) is not so helpful, as it only says
```
--properties
Properties of linked service. Expected value: json-string/@json-file.
```

## Steps to reproduce

Running the command 

```powershell
az datafactory linked-service create --factory-name "dataFactory" \
                                  --name "adfaml" \
                                  --resource-group "adf" \
                                  --properties "{ \
                                      \"type\":\"AzureMLService\", \
                                      \"typeProperties\": { \
                                        \"subscriptionId\": \"XXXXX\", \
                                        \"resourceGroupName\": \"adf-rg\", \
                                        \"mlWorkspaceName\": \"mlWorkspace\", \
                                        \"authentication\": \"MSI\" \
                                     } \
                                  }"
```
results to this (in data factory):

```yaml
{
    "name": "adfaml",
    "type": "Microsoft.DataFactory/factories/linkedservices",
    "properties": {
        "type": "AzureMLService",
        "typeProperties": {
            "subscriptionId": "XXXXX",
            "resourceGroupName": "adf-rg",
            "mlWorkspaceName": "mlWorkspace"
        },
        "annotations": []
    }
}
```
The property `"authentication": "MSI"` is missing. By testing the connection you will get this error:

```
Error code: 9512
Details: AzureMLService linked service has invalid value for property 'servicePrincipalId'.
```

After adding the MSI over the UI the yaml will change to this:
```yaml
{
    "name": "adfaml",
    "type": "Microsoft.DataFactory/factories/linkedservices",
    "properties": {
        "type": "AzureMLService",
        "typeProperties": {
            "subscriptionId": "XXXXX",
            "resourceGroupName": "adf-rg",
            "mlWorkspaceName": "mlWorkspace",
            "authentication": "MSI"
        },
        "annotations": []
    }
}
```
and the connection check works.

## Environment data

```powershell
azure-cli                         2.25.0

core                              2.25.0
telemetry                          1.0.6

Extensions:
azure-cli-ml                      1.29.0
datafactory                        0.3.0
```
