### ISSUE TITLE
Get-AzLocation, ISO 3166 for Azure Regional Locations and other known abbreviations

### ISSUE THREAD

**Issue by ericcsinger** [Azure/azure-powershell#15869]
## Description of the new feature
Azures regional names, can be difficult to incorporate into resources, without causing conflict, or running out of chars.  For example, a storage account name must be globally unique + be less than 20 chars.

In the idea of making Azure more programmable and standardized, it would be awesome if we could get a few additional properties about the azure locations.   Since the information is already [here](https://azure.microsoft.com/en-us/global-infrastructure/geographies/#geographies), why not make it available in PS

## Proposed implementation details (optional)
Add the following properties to the locations database to aid in programmatic names based on location. 
- ISO3166-1 (Country Codes) as linked [here](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes)
- ISO3166-2 (City Codes) as linked in the subs of those given countries.  For example, [Norway](https://en.wikipedia.org/wiki/Counties_of_Norway)
- The region number if there are multiple locations in the same region.  For example, EastUS and EastUS2 are both in Virginia.  In that case, have a region number property of 0 and 2 respectively.
- Have the friendly name for the country and state / city of the region
- Have the cardinal properties broken out, for example, the direction and degrees, see more [here](https://en.wikipedia.org/wiki/Cardinal_direction)

Example:
```YAML
Location:  "norwaywest"
DisplayName: "Norway West"
CountryName: "Norway"
City: "Oslo"
ISO31661Alpha2: "NO"
ISO31661Alpha3: "NOR"
ISO31661Num: 578
ISO31662Code: 03
CardinalDirection: West
CardinalDegree: 270
```
