### ISSUE TITLE
"Your Azure credentials have not been set up or have expired" when using workload federation in GitHub Actions

### ISSUE THREAD

**Issue by daltondhcp** [Azure/azure-powershell#17346]
### Description

Related to https://github.com/azure/azops that takes a dependency on Az.PowerShell for deployments and template generation. 

After starting to authenticate with the [workload federation feature](https://github.com/azure/login#sample-workflow-that-uses-azure-login-action-using-oidc-to-run-az-powershell-windows) for the service principal used in the action (effectively removing the client secret from GitHub), the long-running "Pull" actions fail with the error message below: 
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/16622613/156622571-591149e1-340c-4d6a-b69d-61e9901f96e9.png">

We use the azure/login@v1 action with the enable-AzPSSession set to true to authenticate - seems to be connecting with  `Connect-AzAccount -ServicePrincipal -ApplicationId '***' -Tenant '***' -FederatedToken '***'` under the hood. 
```yaml
- name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
        uses: azure/login@v1
        with:
          client-id: ${{ env.ARM_CLIENT_ID}}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }} 
          enable-AzPSSession: true
```

Reverting to connecting with Connect-AzAccount -ServicePrincipal and a regular ClientId/Secret resolves the issue. 

Downstream issue: https://github.com/Azure/AzOps/issues/541

### Issue script & Debug output

```PowerShell
See https://github.com/azure/azops
```

### Environment data

```PowerShell
Operating System
  Ubuntu
  20.0[4]
  LTS
Virtual Environment
  Environment: ubuntu-20.04
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20220227.1/images/linux/Ubuntu2004-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20220227.1

PowerShell 7.2.1
```

### Module versions

```PowerShell
Name                Version    Repository InstalledDate
----                -------    ---------- -------------
Az.Accounts         2.7.2      PSGallery  03/03/2022 12:39:02
Az.Billing          2.0.0      PSGallery  03/03/2022 12:39:06
Az.Resources        5.3.1      PSGallery  03/03/2022 12:39:09
```
