### ISSUE TITLE
Unable to disable local account on AKS cluster using Az.Aks

### ISSUE THREAD

**Issue by MKruger777** [Azure/azure-powershell#21835]
### Description

I am trying to enable the local account on an AKS cluster (version 1.24.10) by running commands from an AzureDevOps yaml pipeline.

The “old” `az aks command : az aks update -g <myresourcegroup> -n <myclustername> --enable-local` used to serve me well to enable a local account on an AKS cluster. In the yaml pipeline, however, this does not seem to work and I resorted to running the [Set-AzAksCluster](https://learn.microsoft.com/en-us/powershell/module/az.aks/set-azakscluster?view=azps-9.7.1) command from within a AzurePowerShell@5 task

````
- task: AzurePowerShell@5
    displayName: 'disable-local-account'
    name: disablelocalaccount
    inputs:
      azureSubscription: 'myazsubscription' 
      ScriptType: InlineScript
      Inline: |
          Set-AzAksCluster -ResourceGroupName myresourcegrp -Name mycluster -DisableLocalAccount
      azurePowerShellVersion: LatestVersion
````

By passing the -DisableLocalAccount switch to the command we can disable the local account on the cluster. The enabling of the local account on the cluster just seems to elude me somehow…sigh.

Does anybody know if it is possible to enable the local account using the [Set-AzAksCluster](https://learn.microsoft.com/en-us/powershell/module/az.aks/set-azakscluster?view=azps-9.7.1) command? And if so, what is the correct way to go about this?

Many thanks!

Kind regards,
Morné
