### ISSUE TITLE
Missing Install-Module after call to Clear-AzContext

### ISSUE THREAD

**Issue by onetocny** [Azure/azure-powershell#26628]
### Description

We are the team that maintains [AzurePowerShell task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-powershell-v5?view=azure-pipelines) for Azure Pipelines. Under the hood the task is using `Az.Accounts` module to authenticate against Azure and then calls the client script. Recently we started to see several customers having intermittent issues with missing `Install-Module` command when trying to use it within the client script of the AzurePowerShell task (see the issue script section).

```pwsh
Install-Module: /home/vsts/work/_temp/7300057a-5dec-4a53-a079-f60c018950c0.ps1:5
Line |
   5 |  Install-Module -Name Az.ResourceGraph -Scope CurrentUser -SkipPublish …
     |  ~~~~~~~~~~~~~~
     | The term 'Install-Module' is not recognized as a name of a cmdlet,
     | function, script file, or executable program. Check the spelling of the
     | name, or if a path was included, verify that the path is correct and try
     | again.
```

The issue occurs in approximately one quarter of all cases on Ubuntu 22.04 (see the environment data table below). We did some investigation and found out that `Install-Module` command becomes unavailable once the `Clear-AzContext` is called. Also we noticed that calling `Get-Command "Install-Module" -ErrorAction SilentlyContinue` mitigates the issue and `Install-Module` becomes available again.

### Issue script & Debug output

# this is done by task
$module = Get-Module -Name "Az.Accounts" -ListAvailable | Sort-Object Version -Descending | Select-Object -First 1
$module = Import-Module -Name $module.Path -Global -PassThru -Force
$null = Clear-AzContext -Scope Process
# client part
Install-Module -Name Az.ResourceGraph -Scope CurrentUser -SkipPublisherCheck -Force

### Environment data

Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Ubuntu 22.04.5 LTS
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### Module versions

Name              : Az.Accounts
Path              : /usr/share/az_12.1.0/Az.Accounts/3.0.4/Az.Accounts.psm1
Description       : Microsoft Azure PowerShell - Accounts credential management
                     cmdlets for Azure Resource Manager in Windows PowerShell a
                    nd PowerShell Core.
                    
                    For more information on account credential management, plea
                    se visit the following: https://learn.microsoft.com/powersh
                    ell/azure/authenticate-azureps
Guid              : 17a2feff-488b-47f9-8729-e2cec094624c
Version           : 3.0.4
ModuleBase        : /usr/share/az_12.1.0/Az.Accounts/3.0.4
ModuleType        : Script
PrivateData       : {[PSData, System.Collections.Hashtable]}
AccessMode        : ReadWrite
ExportedAliases   : {[Add-AzAccount, Add-AzAccount], [Get-AzDomain, Get-AzDomai
                    n], [Invoke-AzRest, Invoke-AzRest], [Login-AzAccount, Login
                    -AzAccount]…}
ExportedCmdlets   : {[Add-AzEnvironment, Add-AzEnvironment], [Clear-AzConfig, C
                    lear-AzConfig], [Clear-AzContext, Clear-AzContext], [Clear-
                    AzDefault, Clear-AzDefault]…}
ExportedFunctions : {}
ExportedVariables : {}
NestedModules     : {Microsoft.Azure.PowerShell.Cmdlets.Accounts}

### Error output

There are no errors in Az module.

**Comment by o-l-a-v** [comment]
On the client part when this happens, what is the output of:

```pwsh
# List paths PowerShell will use to check for loading modules
$env:PSModulePath.Split(';')

# Can PowerShell find PowerShellGet and PSResourceGet be found?
Get-Module -ListAvailable -Name 'PowerShellGet', 'Microsoft.PowerShell.PSResourceGet' |
    Sort-Object -Property 'Name', 'Version' |
    Format-List -Property 'Name', 'Version', 'Path'
```

I'd also recommend to use `Install-PSResource` ( <https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.psresourceget/install-psresource> ) of PSResourceGet ( <https://github.com/PowerShell/PSResourceGet> ), as PowerShellGet and PackageManagement has been superseded.

I think PowerShellGet v3 is meant to create backward compatible aliases to PSResourceGet, but it does not look finished / still in beta:

* <https://github.com/PowerShell/PowerShellGet>
* <https://www.powershellgallery.com/packages/PowerShellGet>

**Comment by VeryEarly** [comment]
@dolauli to reproduce

**Comment by dolauli** [comment]
> (I'm not a maintainer, just a curious user.)
> 
> On the client part when this happens, what is the output of:
> 
> # List paths PowerShell will use to check for loading modules
> [System.Environment]::GetEnvironmentVariable('PSModulePath','Process').Split(';')
> 
> # Can PowerShellGet and PSResourceGet be found?
> Get-Module -ListAvailable -Name 'PowerShellGet', 'Microsoft.PowerShell.PSResourceGet' |
>     Sort-Object -Property 'Name', 'Version' |
>     Format-List -Property 'Name', 'Version', 'Path'
> I'd also recommend using `Install-PSResource` ( https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.psresourceget/install-psresource ) of PSResourceGet ( https://github.com/PowerShell/PSResourceGet ), as PowerShellGet and PackageManagement has been superseded.
> 
> I think PowerShellGet v3 is meant to create backward compatible aliases to PSResourceGet ( `PowerShellGet\Install-Module` => `Microsoft.PowerShell.PSResourceGet\Install-PSResource` ), but it does not look finished / still in beta:
> 
> * https://github.com/PowerShell/PowerShellGet
> * https://www.powershellgallery.com/packages/PowerShellGet
> 
> Edit: Maybe relevant, seems you combine PSModulePath in function `Update-PSModulePathForHostedAgentLinux` with `:`, not semicolon `;`? 🤔
> 
> * https://github.com/microsoft/azure-pipelines-tasks/blob/feaa563ebc1ee577e4544b8bbf5f90c12089fb71/Tasks/AzurePowerShellV5/Utility.ps1#L86-L105

It's correct. In Linux, it use `:` instead of `;`.

**Comment by dolauli** [comment]
@onetocny Does the task run in a docker container? If it is, could you share with us your docker image and with steps how to reproduce the issue?

**Comment by onetocny** [comment]
@dolauli Task runs on MS hosted VM. No container is used. The issue might be reproduced by creating following Azure Devops pipeline:

```yml
trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
- name: attempts
  type: object
  default:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19

jobs:
- ${{ each attempt in parameters.attempts }} :
  - job: 
    displayName: Attempt ${{ attempt }}
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          $env:PSModulePath = "/usr/share/az_12.1.0:/home/vsts/.local/share/powershell/Modules:/usr/local/share/powershell/Modules:/opt/microsoft/powershell/7/Modules"
          $moduleName = "Az.Accounts"
          $module = Get-Module -Name $moduleName -ListAvailable | Sort-Object Version -Descending | Select-Object -First 1
          $module = Import-Module -Name $module.Path -Global -PassThru -Force
          $null = Clear-AzContext -Scope Process
          Install-Module -Name Az.ResourceGraph -Scope CurrentUser -SkipPublisherCheck -Force
```

Attempts are added to increase a chance to hit the issue as it does not occur always.
