### ISSUE TITLE
Need to document paramter aliases for New-AzureRmStorageAccountKey

### ISSUE THREAD

**Issue by sdwheeler** [Azure/azure-powershell#4746]
### Cmdlet(s)
New-AzureRmStorageAccountKey
Module: AzureRM.Storage

### PowerShell Version
Current 

### Description
LiveFyre comment:
>There is no parameter named "-AccountName", and the flawed code example probably means "-Name". Thanks.

"StorageAccountName" and "AccountName" are aliases for the "Name" parameter. But that should be documented.

**Comment by cormacpayne** [comment]
@sdwheeler Hey Sean, this is documented for the `Name`  parameter in the `Aliases` property:

### -Name
Specifies the name of the Storage account for which to regenerate a storage key.

```yaml
Type: String
Parameter Sets: (All)
Aliases: StorageAccountName, AccountName

Required: True
Position: 1
Default value: None
Accept pipeline input: True (ByPropertyName)
Accept wildcard characters: False
```

Are you saying that the example should be changed from `AccountName` to `Name`?
