### ISSUE TITLE
Container fails to create in Kubernetes

### ISSUE THREAD

**Issue by justinhauer** [Azure/azure-powershell#6943]
### Description
azuresdk/azure-powershell-core:latest container image fails to create in kubernetes. Image works fine when running docker locally but when scheduling in kubernetes, image fails to build: 

```
tagging-1534357500-sdj4f   0/1       ContainerCreating   0          3s
kubectl logs tagging-1534357500-d8s4z
Failed to initialize CoreCLR, HRESULT: 0x80004005
```

### Script/Steps for Reproduction

```
kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: tagging
  namespace: default
spec:
  schedule: '*/1 * * * *'
  startingDeadlineSeconds: 30
  concurrencyPolicy: Forbid
  suspend: false
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            parent: tagging
        spec:
          containers:
          - name: tagging2
            image: azuresdk/azure-powershell-core:latest
            command:
              - pwsh
              - -File
              - /tmp/myscript.ps1
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - name: azuretags
                mountPath: /tmp/
          volumes:
            - name: azuretags
              configMap:
                 name: azuretags
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
          schedulerName: default-scheduler
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1

```

### Module Version

not applicable
`
### Environment Data
not applicable

### Debug Output

```

```
